import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>재영소프트</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <a href="/">회사소개</a>
          <br />
          <a href="/events">사업영역</a>
          <br />
          <a href="/about-me">상시채용</a>
          <br />
          <a href="/about-me">재영소식</a>
          <br />
          <a href="/about-me">CONTACT</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href="/">
          <img />
          <h2> 재영소프트 logo</h2>
          <p>미래를 준비하는 강한 IT기업, 재영소프트</p>
        </a>
        <div className="intro-biz">
          <h3>재영소프트 사업분야 소개</h3>
          <p>
            대한밀국 IT 산업을 이끌어가는 재영소프트의 다양한 사업분야를
            소개합니다.
          </p>

          <a href="/">
            <img />
            <h2> 차세대사업</h2>
            <p>4차 산업혁명 시대에 대비하는 선도 과제를 수행합니다.</p>
          </a>
          <a href="/">
            <img />
            <h2> SI 사업</h2>
            <p>
              지속적인 프로젝트 수행역량 강화로 고객 비즈니스에 최적화된
              시스템을 구축합니다.
            </p>
          </a>
          <a href="/">
            <img />
            <h2> 솔루션사업 사업</h2>
            <p>
              고객의 니즈를 충족하는 솔루션을 구현하여 비즈니스 성과를 극대화
              합니다.
            </p>
          </a>
        </div>

        <div className="재영소프트 가치관">
          <p>세상을 한발 앞서가는 글러벌 기업 재영소픝</p>
          <p>
            인간과 기술을 존중하며 고객을 제일로 하는 기업이념을 실천해 온 저희
            회사는 신뢰와 성실, 믿음과 중요의 이념을 준수하여
          </p>
          <br />
          <p>
            최고의 품질과 기술력으로 풍요롭고 행복한 미래 사회를 창조해 나아갈
            것입니다.
          </p>
          {/* <Icon>신뢰</Icon> */}
          {/* <Icon> 성실</Icon> */}
          {/* <Icon>믿음</Icon> */}
          {/* <Icon>중용</Icon> */}
          {/* <Button>자세히 보기</Button> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <div>
          <p class="jy">(주)재영소프트</p>
          <address>
            서울시 영등포구 선유로13길 25 911호(문래동6가 에이스하이테크시티2)
            <span class="number">
              <br />
              대표전화: 070-4369-5880 팩스: 070-4369-5881
            </span>
          </address>
          <p class="copy">© Copyright JaeYoung Soft. All right reserved.</p>
        </div>
      </footer>
    </div>
  );
}
